server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql:///shop
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: user_service
  registry:
    address: zookeeper://192.168.226.180:2181
  protocol:
    name: dubbo
    port: -1
  provider:
    timeout: 10000